block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
    "build (stable, aarch64-unknown-linux-gnu)",
    "build (stable, arm-unknown-linux-gnueabi)",
    "build (stable, armv7-unknown-linux-gnueabihf)",
    "build (stable, i686-unknown-linux-gnu)",
    "build (stable, i686-unknown-linux-musl)",
    "build (stable, mips-unknown-linux-gnu)",
    "build (stable, mips64-unknown-linux-gnuabi64)",
    "build (stable, mips64el-unknown-linux-gnuabi64)",
    "build (stable, mipsel-unknown-linux-gnu)",
    "build (stable, powerpc-unknown-linux-gnu)",
    "build (stable, powerpc64le-unknown-linux-gnu)",
    "build (stable, s390x-unknown-linux-gnu)",
    "build (stable, x86_64-unknown-linux-gnu)",
    "build (stable, x86_64-unknown-linux-musl)",

    "build (1.59.0, x86_64-unknown-linux-gnu)",

    "checks"
]
timeout_sec = 7200
