# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=gpio-cdev

branches:
  only:
    - master
    - staging
    - trying

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Android (disabled for now due to nix issues)
    # - env: TARGET=aarch64-linux-android DISABLE_TESTS=1
    # - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1
    # - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    # - env: TARGET=i686-linux-android DISABLE_TESTS=1
    # - env: TARGET=x86_64-linux-android DISABLE_TESTS=1

    # TODO: Add back when we have a MacOS stub implementaiton
    # - env: TARGET=i686-apple-darwin
    #   os: osx
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx

    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=arm-unknown-linux-gnueabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=armv7-unknown-linux-gnueabihf
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=i686-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=i686-unknown-linux-musl
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=mips-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=mips64-unknown-linux-gnuabi64
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=mips64el-unknown-linux-gnuabi64
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=mipsel-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=powerpc-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=powerpc64-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=powerpc64le-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=x86_64-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
    - env: TARGET=x86_64-unknown-linux-musl
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "ZZdMvl1P0aryrEKReoR4wApMHw48+9Z843+4G/vmEDvqj0ogZ7ryDZ49gHiEc0cV7QHXE/OIBLIYtS9WVIDZ4h7HTLke5IdhB1pvOJX1dovQfxIZaR66Z9pVvcIJ/KOVgkxAzqd8WrcI/uvLnSH4VWflu0D1X10Ry7j6xZjVByhwh9ObNktklCkQWDbt19fABpRJZ0aZjj2djzlSpLWiYeg0Dj6GnrDp4fBki8LCQmJtE1QcEb83fegfyLPCT4/eI1f4vwayJ/6RhMtMbYcNWs8B0tuaPvYuzBZWwRsN2cMz6BrIiMO0CjOa8tjl6kCnrlOqd84wdE8l9/TTx6Scjwrii/xN2heOhbeOOXe8DElmL3JmUvRzMtK8idwGSYAyqWWiTojwPsVF3IylCANQJhcSyymtANl4OqD1kxtdUY3kvWH675fbi2iJt1uaAv8ZnjesMjzhnCcUYF7NIfuif0VWOqaBbG9T+39rBav8quqWwWJUqytk3kI/rqdlVGsNWWeeM6ZqstQuZHtTIuzOmgI8VNyKlKIWLJJzlD+t2rvr0FD+iOstwxEKiY1Hhh8naOR1+cJg8jekLDJl6wLKR/7oIXlPJ5csm0086MNQ68K1NLqmA6qPzb2B3V8HCwW/vhw6M2pXSqKqziwd2iLn7TdOezX8nY56NA/ty0EtHYA="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
